### ISSUE TITLE
token returns html

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/hms_field#5] opened 2024-01-10 16:41 UTC
The token for a html_field returns also HTML: `<span class="hms hms-format-h-mm">12:25</span>`, at least with auto_nodetitle.

**Comment by argiepiano** [comment] 2024-01-10 17:06
@robertgarrigos please try the following:
1. Go to the Manage display screen for your content type
2. Edit TOKENS Display mode in that screen
3. Click configure for the HMS field and select None for the wrappers

Try again and report here please

<img width="1227" alt="Screen Shot 2024-01-10 at 10 05 28 AM" src="https://github.com/backdrop-contrib/hms_field/assets/9938978/7d1ed2cd-5ec7-4074-80b4-9403c784aba9">

<img width="1214" alt="Screen Shot 2024-01-10 at 10 05 58 AM" src="https://github.com/backdrop-contrib/hms_field/assets/9938978/ff47631c-fab4-40f6-8fea-130f613d9f82">

**Comment by robertgarrigos** [comment] 2024-01-11 17:58
mmm I don't have the TOKENS display mode.

**Comment by argiepiano** [comment] 2024-01-11 18:00
@robertgarrigos, that's standard in all Backdrop installations, unless you have deleted it or your site is a D7 upgrade (perhaps). It may be disabled. If you don't have it, just create it. Be sure the machine name is `token`.

<img width="1219" alt="Screen Shot 2024-01-11 at 10 59 33 AM" src="https://github.com/backdrop-contrib/hms_field/assets/9938978/4e113ccf-fa9e-45b9-a42e-468dcdcfa9bf">

**Comment by robertgarrigos** [comment] 2024-01-11 18:04
Sorry, looking in a catalan site and translation is confusing ;-)

I don't see the field wrappers

![Cursor_and_LanguageTool_Underlines_Overlay](https://github.com/backdrop-contrib/hms_field/assets/105581/86cb51f9-949e-44ca-b228-358811fb3636)

**Comment by argiepiano** [comment] 2024-01-11 18:16
Ah, actually those wrappers are provided by a different module and have nothing to do with the problem you reported (and won't fix that either). I'll take a look at this. I think the issue is that Backdrop's  field tokens use the markup provided by the field type, and those html tags are hard-coded into the hms theming functions. I'll have to take a closer look.

**Comment by argiepiano** [comment] 2024-01-11 18:28
@robertgarrigos, as a quick temporary fix, you can override `theme_hms()` in your theme's template.php file. Copy the content of `theme_hms()` (rename, for example, `basis_hms()`), and remove the hard-coded html tags added there.

This change will make all HMS fields and tokens output without that `<span>`. You could add some logic there (for example checking the display mode - if it's `token`, then skip adding the span, otherwise, add that normally.

Fixing this will require some mid-size changes to the module (e.g. adding the option to customize the markup in the Display modes menus), and I don't have the time to do that now.

Let me know if this doesn't work for you.

**Comment by robertgarrigos** [comment] 2024-01-12 16:16
Thanks @argiepiano that would be enough for me now

**Comment by robertgarrigos** [comment] 2024-01-12 16:39
mmm I don't see how to get the display mode within my custom_hms function.

**Comment by argiepiano** [comment] 2024-01-12 16:42
Can you paste the whole overriding function? Also, where is this function?

**Comment by argiepiano** [comment] 2024-01-12 16:55
I see - yes, the view mode is not available to the theming function. So, at this point, this span removal will affect all view modes. This can be solved by adding new settings to the formatter function...

**Comment by argiepiano** [comment] 2024-01-12 18:37
@robertgarrigos I've merged a PR that adds a setting to the formatter configuration. Can you please use the dev version of the module and test?

1. The setting adds the span by default for backward compatibility
2. You can now edit the Tokens display mode, and change the span setting to "No" there
4. Be sure to click UPDATE and then SAVE the display mode to apply

Then try adding the token using auto_nodetitle and let me know.

<img width="964" alt="Screen Shot 2024-01-12 at 11 38 09 AM" src="https://github.com/backdrop-contrib/hms_field/assets/9938978/06206a2e-2a7f-4443-b00a-3ca339a3f15c">

**Comment by robertgarrigos** [comment] 2024-01-13 10:36
Thanks, @argiepiano it works as expected.

**Comment by argiepiano** [comment] 2024-01-13 15:03
Great! I'll do a new release

**Closed as completed** 2024-01-13 15:04 UTC
